config/routes.rb
require 'api/api'

Olb::Application.routes.draw do
  
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root :to => 'home#index'

  get "/404", :to => "errors#not_found"
  get "/500", :to => "errors#internal_error"

  get "/work_for_period" => 'home#work_for_period', as: 'work_for_period'

  resource :profile, only: [:show, :edit, :update] do
    scope module: :profiles do
      resource :avatar, only: [:destroy]
      resource :password, only: [:edit, :update]
    end
  end

  get "/users/:id/avatar" => "users#avatar"


  resources :projects do
    put :remove_attachment
    get :show_export
    get :export
    scope module: :projects do
      resources :members
      resources :tasks
      resources :stats, only: [:index, :show]
      resource  :timesheet do
        get :tasks
      end
    end
  end

  namespace :admin do
    resources :projects, only: [:index]
    resources :users do
      put :remove_avatar
    end
    resources :settings, only: [:index, :edit]
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                      :integer          not null, primary key
#  code                    :string(255)      default(""), not null
#  name                    :string(255)      default(""), not null
#  description             :text
#  created_at              :datetime
#  updated_at              :datetime
#  attachment_file_name    :string(255)
#  attachment_content_type :string(255)
#  attachment_file_size    :integer
#  attachment_updated_at   :datetime
#  state                   :string(255)
#

class Project < ActiveRecord::Base
  has_attached_file :attachment, :styles => { :medium => "160x180#", :thumb => "100>", :small_thumb => "50x50#" }

  has_many :project_members, dependent: :destroy
  has_many :users, through: :project_members
  has_many :tasks, dependent: :destroy
  has_many :project_snapshots, dependent: :destroy
  has_many :project_openings, dependent: :destroy


  #
  # Validations
  #
  validates :code, presence: true
  validates_uniqueness_of :code
  validates_length_of :code, :maximum => 8
  validates :name, presence: true
  validates_attachment_content_type :attachment, :content_type => /\Aimage/
  validates_attachment_size :attachment, :in => 0.kilobytes..200.kilobytes

  #
  # States
  #
  state_machine :state, initial: :draft do
    event :openit do
      transition all => :opened
    end

    event :closeit do
      transition :opened => :closed
    end
  end

  #
  # Scopes
  #
  scope :opened, -> { where(state: "opened") }

  def picture_url
    attachment.url
  end

  def original_estimate
    tasks.sum(:original_estimate)
  end

  def work_logged
    resu = 0
    found = Task.includes(:work_logs).where('project_id=?', id)
    found.each do |task|
      resu += task.work_logged
    end
    return resu
  end

  def delta
    resu = 0
    found = Task.includes(:work_logs).where('project_id=?', id)
    found.each do |task|
      resu += task.delta
    end
    return resu
  end

  def remaining_estimate
    tasks.sum(:remaining_estimate)
  end

  def total
    work_logged + remaining_estimate
  end

  def progress
    total > 0 ? work_logged * 100 / total : 0
  end

  def touch_opening(user_id)
    opening = project_openings.find_by user_id: user_id
    unless opening
      opening = ProjectOpening.new
      opening.user_id    = user_id
      opening.project_id = id
    end
    opening.touched = Random.rand(9999)
    opening.save
  end

  def find_member(user)
    project_members.find_by(user_id:user.id)
  end

  # Create a snapshot of all opened projects
  def self.snapshot
    Project.opened.each do |project|
      snap = ProjectSnapshot.new
      snap.project            = project
      snap.task_count         = project.tasks.count
      snap.original_estimate  = project.original_estimate
      snap.work_logged        = project.work_logged
      snap.remaining_estimate = project.remaining_estimate
      unless snap.save
        logger.error snap.errors.messages
      end
    end
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Projects", :admin_projects_path

  def index
    @projects = Project.order(:name).page(params[:page])
  end

end

app/controllers/projects/items_controller.rb
class Projects::ItemsController < ApplicationController
  before_action :project
  layout "project"

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Projects", :projects_path

  protected

  def add_project_breadcrumb
    add_breadcrumb @project.name, project_path(params[:project_id])
  end

  def project
    @project = Project.find(params[:project_id])
    return render_404 unless can?(current_user, :read_project, @project) 

    @project.touch_opening(current_user.id)
    gon.project_id    = @project.id
    gon.project_state = @project.state
  end

end

app/controllers/projects/members_controller.rb
class Projects::MembersController < Projects::ItemsController

  def index
    @members = @project.project_members.by_name.page(params[:page])
    @member = ProjectMember.new
    add_project_breadcrumb
    add_breadcrumb "Members", :project_members_path
    init_new_options
  end

  def new
    return render_404 unless can?(current_user, :create_project_member, @project)

    add_new_breadcrumb
    init_new_options
    @errors = []
  end

  def create
    return render_404 unless can?(current_user, :create_project_member, @project)

    ids = params['user-search'].split(',').map { |s| s.to_i } 
    @errors = []
    if ids.empty?
      @errors << "You must select at least one user"
    else
      ids.each do |id|
        if @project.users.exists?(id)
          user = User.find(id)
          @errors << "User #{user.name} is already a member of this project" 
        end
      end
    end

    unless can?(current_user, :create_project_member_admin, @project)
      if params[:role] == 'admin'
        @errors << "You are not allowed to give admin role"
      end
    end

    if @errors.any?
      add_new_breadcrumb
      init_new_options
      return render "new" 
    end

    ids.each do |id|
      member = ProjectMember.new
      member.user = User.find(id)
      member.project = @project
      member.role = params[:role]
      member.save
    end
    flash[:notice] = "Members was successfully added"

    redirect_to project_members_path
  end

  def update
    return render_404 unless can?(current_user, :update_project_member, @project)
    member = ProjectMember.find(params[:id])

    project = member.project
    can_update = member_params[:role] == 'admin'

    unless can_update
      project.project_members.each do |current|
        if current.id != member.id && current.role == 'admin'
          can_update = true
        end
      end
    end

    if can_update
      if member.update_attributes(member_params)
        flash[:notice] = "Member role was successfully updated"
      end
    else
      flash[:alert] = "Member role was not updated. A project must have at least one admin"
    end

    redirect_to project_members_path
  end


  def destroy
    return render_404 unless can?(current_user, :delete_project_member, @project)
    member = ProjectMember.find(params[:id])
    if member.assigned_tasks.count == 0
      if member.destroy
        flash[:notice] = "Member was successfully removed"
      end
    else
      flash[:alert] = "Can't delete member with assigned tasks"
    end
    redirect_to project_members_path
  end

  private

  def init_new_options
    @new_options = [:guest, :developer, :master]
    @new_options << :admin if can?(current_user, :create_project_member_admin, @project)
  end

  def add_new_breadcrumb
    add_project_breadcrumb
    add_breadcrumb "Members", :project_members_path
    add_breadcrumb "New", :new_project_member_path
  end


  def member_params
    params.require(:project_member).permit(:role)
  end
end

app/controllers/projects/stats_controller.rb
class Projects::StatsController < Projects::ItemsController
  def index
    add_project_breadcrumb
    add_breadcrumb "Statistics", :project_stats_path
  end

  def show
    period_start = params[:start]
    period_end   = params[:end]

    first = Date.strptime(period_start, '%Y%m%d')
    last  = Date.strptime(period_end, '%Y%m%d')

    if (last - first).to_i > 366
      @error = "Maximum allowed range is 366 days."
    else
      @members = @project.project_members

      # create an empty two dimensional array
      # columns are for members
      # rows are for days
      @results = Array.new
      @js_results = Array.new

      first.upto(last) do |date|
        row    = Array.new(@members.size + 1, 0)
        row[0] = date.strftime("%b %d, %Y")
        @results << row
        
        js_hash = Hash.new
        js_hash['day'] = date.strftime("%Y-%m-%d")
        @members.each do |member|
          js_hash[member.email] = 0
        end
        @js_results << js_hash
      end

      @total = Array.new(@members.size, 0)

      # fill array
      @members.each_with_index do |member, index|
        logs = member.work_logs(period_start, period_end)
        logs.each do |log|
          date = Date.strptime(log.day, '%Y%m%d')
          diff = (date - first).to_i
          @results[diff][index+1] = view_context.duration(log.total_worked)
          @js_results[diff][member.email] = view_context.to_days(log.total_worked)

          @total[index] += log.total_worked
        end
      end

      @total.each_with_index do |item, index|
        @total[index] = view_context.duration(item)
      end
    end

    respond_to do |format|
      format.html { render :layout => !request.xhr? }
    end

  end
end

app/controllers/projects/tasks_controller.rb
class Projects::TasksController < Projects::ItemsController

  def index
    add_project_breadcrumb
    add_breadcrumb "Tasks", :project_tasks_path

    gon.user_id                  = current_user.id
    gon.can_update_tasks         = can?(current_user, :update_project_task,  @project)
    gon.can_take_unassigned_task = can?(current_user, :take_unassigned_task, @project)
  end

end

app/controllers/projects/timesheets_controller.rb
class Projects::TimesheetsController < Projects::ItemsController

  # Start editing timesheet
  def edit
    add_project_breadcrumb
    add_breadcrumb "My Timesheet", :edit_project_timesheet_path

    today = Date.today
    @period_start    = today.beginning_of_week
    @period_end      = @period_start + 4
    gon.user_id      = current_user.id
    gon.period_start = @period_start.strftime("%Y%m%d")
    gon.period_end   = @period_end.strftime("%Y%m%d")
    gon.can_update_members_task_work = can?(current_user, :update_members_task_work, @project)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :project, only: [:show, :edit, :update, :destroy]

  layout "project", only: [:show, :show_export]

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Projects", :projects_path

  def index
    @projects = current_user.projects.order(:name).page(params[:page])
  end

  def show
    add_breadcrumb @project.name, :project_path
  end

  def new
    add_breadcrumb "New", :new_project_path
    session[:return_to] = request.referer
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      member = ProjectMember.new
      member.project = @project
      member.user = current_user
      member.role = :admin
      member.save!

      flash[:notice] = "Project was successfully created"
      redirect_to project_path(@project)
    else
      render "new"
    end
  end

  def edit
    return render_404 unless can?(current_user, :update_project, @project)
    add_breadcrumb "Edit #{@project.name}", :edit_project_path
    session[:return_to] = request.referer
  end

  def update
    return render_404 unless can?(current_user, :update_project, @project)
    if @project.update_attributes(project_params)
      flash[:notice] = "Project was successfully updated"
      redirect_to session.delete(:return_to)
    else
      render "edit"
    end
  end

  def destroy
    return render_404 unless can?(current_user, :delete_project, @project)
    if @project.destroy
      flash[:notice] = "Project was successfully removed"
    end
    redirect_to projects_path
  end

  def remove_attachment
    @project = Project.find(params[:project_id])
    return render_404 unless can?(current_user, :update_project, @project)
    @project.attachment = nil
    @project.save
    flash[:notice] = "Picture was successfully removed"
    redirect_to :back
  end

  def show_export
    @project = Project.find(params[:project_id])
    return render_404 unless can?(current_user, :export_project, @project)
    add_breadcrumb @project.name, :project_show_export_path
  end

  def export
    @project = Project.find(params[:project_id])
    return render_404 unless can?(current_user, :export_project, @project)
    respond_to do |format|
      format.xlsx
    end
  end

  private

  def project
    @project = Project.find(params[:id])
    return render_404 unless can?(current_user, :read_project, @project)
    
    @project.touch_opening(current_user.id)
    gon.project_id = @project.id
  end 

  def project_params
    params.require(:project).permit(:name, :code, :description, :state, :attachment)
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects/members_helper.rb
module Projects::MembersHelper
end

app/helpers/projects/stats_helper.rb
module Projects::StatsHelper
end

app/helpers/projects/tasks_helper.rb
module Projects::TasksHelper
  def tasks_callout(project)
    if project.tasks.count == 0
      description = "To create a new task, just clic on the 'Add Task' button. It will create a new line. "
      description << "You can then complete task informations. For estimates, you can enter time in years (e.g., 1y), months (e.g., 3mo), days (e.g., 1d), hours (e.g., 4h) or minutes (e.g., 30m), "
      description << "and of course combine them (e.g., 1y 3mo 1d 4h 30m)."
      description = description.html_safe
      render partial: "shared/callout_info", locals: {title: "No tasks yet", description: description}
    end
  end
end

app/helpers/projects/timesheets_helper.rb
module Projects::TimesheetsHelper
  def format_period(period_start, period_end)
    period_start.strftime("%b %d, %Y") + " - " + period_end.strftime("%b %d, %Y")
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def dashboard_callout(project)
    if project.tasks.count == 0
      description = "Your project doesn't have any task. You should go to the " + link_to("tasks page.", project_tasks_path(project))
      description = description.html_safe
      render partial: "shared/callout_info", locals: {title: "No tasks yet", description: description}
    end
  end

  def options_for_project(project)
    if project.draft?
      ['draft', 'opened']
    else
      ['opened', 'closed']
    end
  end

  def class_for_project_state(project)
    case project.state
    when 'draft'
      'warning'
    when 'opened'
      'success'
    else
      'danger'
    end
  end

  def members_done(project)
    members_done = "["
    project.project_members.by_name.each do |member|
      if member.work_logged > 0 || member.remaining_estimate > 0
        members_done << ","  unless members_done == "["
        name = escape_javascript(member.name)
        members_done << "[#{to_days(member.work_logged)}, '#{name}']"
      end
    end
    members_done << "]"
  end

  def members_remaining(project)
    members_tbd  = "["
    project.project_members.by_name.each do |member|
      if member.work_logged > 0 || member.remaining_estimate > 0
        members_tbd << ","  unless members_tbd == "["
        name = escape_javascript(member.name)
        members_tbd  << "[#{to_days(member.remaining_estimate)}, '#{name}']"
      end
    end
    members_tbd  << "]"
  end

  def tags_done(project)
    worked = Hash.new
    project.tasks.each do |task|
      task.tag_list.each do |tag|
        val = worked[tag] || 0
        val += task.work_logged
        worked[tag] = val
      end
    end

    tags_done = "["
    worked.sort.each do |key,value|
      name = escape_javascript(key)
      tags_done << "," unless tags_done == "["
      tags_done << "[#{to_days(value)}, '#{name}']"
    end
    tags_done << "]"
  end

  def tags_remaining(project)
    remaining = Hash.new
    project.tasks.each do |task|
      task.tag_list.each do |tag|
        val = remaining[tag] || 0
        val += task.remaining_estimate
        remaining[tag] = val
      end
    end

    tags_tbd = "["
    remaining.sort.each do |key,value|
      name = escape_javascript(key)
      tags_tbd << "," unless tags_tbd == "["
      tags_tbd << "[#{to_days(value)}, '#{name}']"
    end
    tags_tbd << "]"
  end

  def user_role(project)
    member = project.find_member(current_user)
    member.nil? ? '' : member.role
  end

end

app/views/projects/_form.html.slim
= form_for(@project, html: { multipart: true }) do |f|
  .col-sm-8.col-md-6
    .box.box-solid
      .box-body
        - if @project.errors.any?
          .alert.alert-danger.alert-dismissable
            button aria-hidden="true" data-dismiss="alert" class="close" type="button" ×
            ul
              - @project.errors.full_messages.each do |msg|
                li = msg
        h4.bottom-15 General Information
        .form-group
          = f.label :code
          = f.text_field :code, :autofocus => true, 'placeholder' => "Enter project code", class: "form-control"
        .form-group
          = f.label :name
          = f.text_field :name, 'placeholder' => "Enter project name", class: "form-control"
        .form-group
          = f.label :description
          = f.text_area :description, rows: "6", class: "form-control"
        .form-group
          = f.label :state
          = f.select :state, options_for_select(options_for_project(@project), @project.state), {}, {class: "form-control"}
        .box-footer.clearfix
          .pull-right
            =link_to "Cancel", session[:return_to]
            | &nbsp;or&nbsp;
            button.btn.btn-primary type="submit" Submit
  .col-sm-8.col-sm-offset-4.col-md-3.col-md-offset-0
    .box.box-solid
      .box-header
        h3.box-title Picture
      .box-body
        - if @project.attachment?
          | You can change project picture here 
          | or remove the current project picture
          .project-picture
            = image_tag @project.attachment.url(:medium)
        - else
          | You can upload a picture here
        hr
        button type="button" class="btn btn-default btn-sm js-choose-project-picture-button"
          i.fa.fa-paperclip
          span  Choose File...
        | &nbsp;
        span.file_name.js-picture-filename  = @project.attachment.original_filename
        = f.file_field :attachment, class: "js-project-picture-input hidden"
        .light The maximum file size allowed is 200KB.
        - if @project.attachment?
          hr
          = link_to 'Remove picture', project_remove_attachment_path(@project), data: { confirm: "Picture will be removed. Are you sure?"}, method: :put, class: "btn btn-danger btn-small remove-picture"
    - if can?(current_user, :delete_project, @project) and @project.id != nil
      .box.box-solid
        .box-header
          h3.box-title Delete project
        .box-body
          =link_to project_path(@project), data: { confirm: "Project will be removed. That can't be undone. Are you sure?"}, method: :delete, class: "btn btn-danger", title: "Delete project"
            i.sign.fa.fa-trash-o.bg-red
            span  Delete project

app/views/projects/_progress.html.slim
.progress.xs data-toggle="tooltip" data-original-title=("#{project.progress}%")
  div class=("progress-bar progress-bar-" + (project.delta < 0 ? "red" : "green")) style=("width:#{project.progress}%") 

app/views/projects/_project_card.html.slim
.thumbnail.project-card
  = render partial: "projects/progress", locals: {project: project}
  = link_to project_path(project) do
    - if project.attachment?
      = image_tag project.attachment.url(:medium), title: project.description, data: {toggle:'tooltip'}
    - else
      = image_tag project.attachment.url(:medium), title: project.description, data: {toggle:'tooltip', src:"holder.js/160x180/text:No picture"}
  .caption
    h3
      = link_to project_path(project),title: project.description, data: {toggle:'tooltip'} do
        = project.name
        small
          |  (
          = project.code
          | )
   
    - project.project_members.by_name.each do |member|
      = image_tag avatar_icon(member.user.email, 38), size:'38', title: member.name, style:'margin:1px', data: {toggle:'tooltip'} 

app/views/projects/_projects_grid.html.slim
.box
  .box-body.table-responsive.no-padding
    table#projects.table.table-hover
      thead
        tr role="row"
          th
          th Code
          th Name
          th Created at
          th Role
          th State
          th Progress
          th Actions
      tbody
        - @projects.each do |project|
          tr 
            td style="width:54px"
              - if project.attachment?
                = image_tag project.attachment.url(:small_thumb), class: "img-rounded"
            td =link_to project.code, project_path(project)
            td =project.name
            td =project.created_at.strftime('%Y-%m-%d')
            td =user_role(project)
            td =project.state
            td
              = render partial: "projects/progress", locals: {project: project}
            td
              - if can?(current_user, :update_project, project)
                =link_to edit_project_path(project), class: "btn btn-primary btn-sm", title: "Edit project"
                  i class="sign fa fa-pencil"
                | &nbsp;
              - if can?(current_user, :delete_project, project)
                =link_to project_path(project), data: { confirm: "Project will be removed. Are you sure?"}, method: :delete, class: "btn btn-danger btn-sm", title: "Delete project"
                  i class="sign fa fa-trash-o bg-red"
  .box-footer.clearfix
    =paginate @projects

app/views/projects/edit.html.slim
- @title="Edit project #{@project.name}"
= render 'form'

app/views/projects/index.html.slim
- @title="Projects"
.row
  .col-sm-2
    .form-group
      =link_to "Add a new project", new_project_path, class: "btn btn-primary btn-block"
    = render '/shared/projects_summary'

  .col-sm-10
    = render '/shared/projects_box'


= render '/shared/project_card'

app/views/projects/new.html.slim
- @title="Create project"
= render 'form'

app/views/projects/show.html.slim
- @title = @project.name
- @subtitle = @project.description
.row
  .col-lg-12
    = dashboard_callout(@project)
.row
  .col-lg-3.col-xs-6
    .small-box.bg-blue
      .inner
        h3 
          = @project.progress
          sup style="font-size:20px"
            | %
        p Project Progress
      .icon
        i.fa.fa-tachometer
  .col-lg-3.col-xs-6
    .small-box.bg-purple
      .inner
        h3 
          = duration(@project.work_logged)
        p Work done
      .icon
        i.fa.fa-check-square-o
  .col-lg-3.col-xs-6
    div  class=(@project.delta < 0 ? "small-box bg-red" : "small-box bg-green")
      .inner
        h3 
          = duration(@project.delta)
        p Project Delta
      .icon
        i.fa.fa-fire
  .col-lg-3.col-xs-6
    .small-box.bg-yellow
      .inner
        h3 
          = @project.project_members.count
        p Members
      .icon
        i.fa.fa-users

.row
  section.col-md-6.connectedSortable.ui-sortable
    .box.box-solid.bg-teal-gradient
      .box-header
        .pull-right.box-tools
          button.btn.bg-teal.btn-sm.pull-right data-widget="collapse" data-toggle="tooltip" title="" style="margin-right: 5px;" data-original-title="Collapse"
            i.fa.fa-minus

        i.fa.fa-tasks
        h3.box-title Burndown Chart (in days)
      .box-body
        #burndown-chart.chart style="height: 250px;"
      .box-footer.no-border
        .row
          .col-xs-4.text-center style="border-right: 1px solid #f4f4f4"
            input type="text" class="knob" data-readonly="true" value=(@project.tasks.not_started.count) data-max=(@project.tasks.count) data-width="60" data-height="60" data-fgColor="#39CCCC"
            .knob-label Tasks not started
          .col-xs-4.text-center style="border-right: 1px solid #f4f4f4"
            input type="text" class="knob" data-readonly="true" value=(@project.tasks.in_progress.count) data-max=(@project.tasks.count) data-width="60" data-height="60" data-fgColor="#39CCCC"
            .knob-label Tasks in progress
          .col-xs-4.text-center
            input type="text" class="knob" data-readonly="true" value=(@project.tasks.done.count) data-max=(@project.tasks.count) data-width="60" data-height="60" data-fgColor="#39CCCC"
            .knob-label Tasks done

    .box.box-danger
      .box-header
        .pull-right.box-tools
          button.btn.bg-red.btn-sm.pull-right data-widget="collapse" data-toggle="tooltip" title="" style="margin-right: 5px;" data-original-title="Collapse"
            i.fa.fa-minus

        i.fa.fa-user
        h3.box-title Progress by members
      .box-body
        #members-chart.chart style="height: 250px;"

  section.col-md-6.connectedSortable.ui-sortable
    .box.box-solid.bg-green-gradient
      .box-header
        .pull-right.box-tools
          button.btn.btn-success.btn-sm.pull-right data-widget="collapse" data-toggle="tooltip" title="" style="margin-right: 5px;" data-original-title="Collapse"
            i.fa.fa-minus

        i.fa.fa-dollar
        h3.box-title Cost Chart (in days)
      .box-body
        #budget-chart.chart style="height: 250px;"
      .box-footer.no-border
        .row
          .col-xs-6.text-center style="border-right: 1px solid #f4f4f4"
            input type="text" class="knob" data-readonly="true" value=(to_days(@project.work_logged)) data-max=(to_days(@project.total)) data-width="60" data-height="60" data-fgColor="#00C46A"
            .knob-label Work logged
          .col-xs-6.text-center style="border-right: 1px solid #f4f4f4"
            input type="text" class="knob" data-readonly="true" value=(to_days(@project.remaining_estimate)) data-max=(to_days(@project.total)) data-width="60" data-height="60" data-fgColor="#00C46A"
            .knob-label Remaining estimate

    .box.box-primary
      .box-header
        .pull-right.box-tools
          button.btn.bg-blue.btn-sm.pull-right data-widget="collapse" data-toggle="tooltip" title="" style="margin-right: 5px;" data-original-title="Collapse"
            i.fa.fa-minus

        i.fa.fa-tags
        h3.box-title Progress by tags
      .box-body
        #tags-chart.chart style="height: 250px;"
javascript:

  var members_done_data = {
    data: #{raw members_done(@project)},
    color: "#f56954"
  }

  var members_tbd_data = {
    data: #{raw members_remaining(@project)},
    color: "#f79f94"
  }

  var tags_done_data = {
    data: #{raw tags_done(@project)},
    color: "#0073B7"
  }

  var tags_tbd_data = {
    data: #{raw tags_remaining(@project)},
    color: "#0798ed"
  }
      

app/views/projects/show_export.html.slim
- @title = @project.name
- @subtitle = @project.description
.row
  .col-lg-12
    .box.box-primary
      .box-header
        h3.box-title Export data
      .box-body
        p
          | If you are anxious of losing your data or want to manipulate them to create your own reports, 
          | you can export all your project data in Open Office XML format.
        p
          | To do so, just click on the button below : 
      .box-footer
        =link_to "Export project data", project_export_path(@project, format: :xlsx), class: "btn btn-primary"