config/routes.rb
require 'api/api'

Olb::Application.routes.draw do
  
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root :to => 'home#index'

  get "/404", :to => "errors#not_found"
  get "/500", :to => "errors#internal_error"

  get "/work_for_period" => 'home#work_for_period', as: 'work_for_period'

  resource :profile, only: [:show, :edit, :update] do
    scope module: :profiles do
      resource :avatar, only: [:destroy]
      resource :password, only: [:edit, :update]
    end
  end

  get "/users/:id/avatar" => "users#avatar"


  resources :projects do
    put :remove_attachment
    get :show_export
    get :export
    scope module: :projects do
      resources :members
      resources :tasks
      resources :stats, only: [:index, :show]
      resource  :timesheet do
        get :tasks
      end
    end
  end

  namespace :admin do
    resources :projects, only: [:index]
    resources :users do
      put :remove_avatar
    end
    resources :settings, only: [:index, :edit]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)      default(""), not null
#  bio                    :string(255)      default(""), not null
#  avatar_file_name       :string(255)
#  avatar_content_type    :string(255)
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  admin                  :boolean          default("f"), not null
#  authentication_token   :string(255)
#

class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2, :github]

  before_create :record_first_admin
  before_save :ensure_authentication_token
  alias_attribute :private_token, :authentication_token

  has_attached_file :avatar, :styles => { :medium => "165x165#", :thumb => "100x100#" }, :default_url => "/images/avatar_missing.png"

  has_many :identities

  has_many :project_members, dependent: :destroy
  has_many :project_openings, dependent: :destroy

  has_many :projects, through: :project_members
  has_many :tasks, :foreign_key => 'assignee_id'

  # Scopes
  scope :admins, -> { where(admin: true) }

  #
  # Validations
  #
  validates :name, presence: true, uniqueness: true
  validates :bio, length: { maximum: 500 }, allow_blank: true         
  validates_attachment_content_type :avatar, :content_type => /\Aimage/
  validates_attachment_size :avatar, :in => 0.megabytes..100.kilobytes

  def is_admin?
    admin
  end

  def attributes
    super.merge({'avatar_url' => avatar_url})
  end

  def avatar_url
    ApplicationController.helpers.avatar_icon(email)
  end

  def ensure_authentication_token
    self.authentication_token ||= generate_authentication_token
  end

  def work_logged
    WorkLog.joins(task: :assignee).select("sum(worked) as work_sum").where(tasks:{assignee_id:id}).take.work_sum || 0
  end

  def work_week(period_start, period_end)
    day_start = period_start.strftime("%Y%m%d")
    day_end   = period_end.strftime("%Y%m%d")
    logs = WorkLog.joins(task: :project).select("project_id, projects.name as name, day, sum(worked) as total_worked").where(day:day_start..day_end).where(tasks:{assignee_id:id}).group("project_id, projects.name, day")
    WorkWeek.new(logs)
  end

  #
  # Class methods
  #
  class << self
    def search query
      where("lower(name) LIKE :query OR lower(email) LIKE :query", query: "%#{query.downcase}%")
    end

    def from_omniauth(auth)
      user = nil
      identity = Identity.where(provider: auth.provider, uid: auth.uid).first
      if identity
        user = identity.user
      else
        user = User.find_by(email: auth.info.email) || User.create(email: auth.info.email, password: Devise.friendly_token[0,20], name: (auth.info.name || auth.info.full_name).to_s)
        identity = Identity.create(provider: auth.provider, uid: auth.uid, user: user)
      end
      user
    end

  end

  private

  # First user is always super admin
  def record_first_admin
    if User.count == 0
      self.admin = true
    end
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :user, only: [:edit, :update, :destroy]

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Users", :admin_users_path

  def index
    gon.user_id = current_user.id
    @users = User.order(:name).page(params[:page])
  end

  def new
    add_breadcrumb "New", :new_admin_user_path
    @user = User.new
  end

  def edit
    add_breadcrumb "Edit", :edit_admin_user_path
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User was successfully created"
      redirect_to admin_users_path
    else
      render "new"
    end
  end

  def update
    if user_params[:password].blank?
      user_params.delete("password")
    end

    successfully_updated = if needs_password?(@user, params)
                             @user.update(user_params)
                           else
                             @user.update_without_password(user_params)
                           end

    if successfully_updated
      flash[:notice] = "User was successfully updated"
      redirect_to admin_users_path
    else
      render "edit"
    end
  end

  def destroy
    user.destroy
    redirect_to admin_users_path
  end

  def remove_avatar
    @user = User.find(params[:user_id])
    @user.avatar = nil
    @user.save
    flash[:notice] = "Avatar was successfully removed"
    redirect_to :back
  end

  protected

  def user
    @user = User.find(params[:id])
  end 

  def user_params
    params.require(:user).permit(:name, :email, :bio, :avatar, :password, :admin)
  end

  # check if we need password to update user data
  # ie if password or email was changed
  # extend this as needed
  def needs_password?(user, params)
    user.email != params[:user][:email] ||
      params[:user][:password].present?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    handle_omniauth("Facebook", "devise.facebook_data")
  end

  def google_oauth2
    handle_omniauth("Google", "devise.google_data")
  end

  def github
    handle_omniauth("Github", "devise.github_data")
  end
private

  def handle_omniauth(kind, session_key)
    @user = User.from_omniauth(request.env["omniauth.auth"].except("extra"))

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: kind) if is_navigational_format?
    else
      session[session_key] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def avatar
    @user = User.find(params[:id])
    @size = params[:size].to_i

    url = view_context.avatar_icon(@user.email, @size)
    data = open(url).read
    send_data data, disposition: 'inline'
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def user_tags(user)
    tags = Array.new
    if user.admin?
      tags.push "admin"
    end
    # TODO : test if blocked
    tags.push "active"
  end
end

app/views/admin/users/_form.html.slim
= form_for([:admin, @user], html: { multipart: true }) do |f|
  .col-sm-8.col-md-6
    .box.box-solid
      .box-body
        - if @user.errors.any?
          .alert.alert-danger.alert-dismissable
            button aria-hidden="true" data-dismiss="alert" class="close" type="button" ×
            ul
              - @user.errors.full_messages.each do |msg|
                li = msg
        h4.bottom-15 General Information
        .form-group
          = f.label :name
          = f.text_field :name, :autofocus => true, 'placeholder' => "Enter user name", class: "form-control"
        .form-group
          = f.label :password, "New password"
          = f.password_field :password, :autofocus => true, 'placeholder' => "Enter user password", class: "form-control"
        .form-group
          = f.label :email
          = f.email_field :email, 'placeholder' => "Enter user email", class: "form-control"
        .form-group
          = f.label :bio
          = f.text_area :bio, rows: "6", class: "form-control"
        .form-group
          = f.check_box :admin, class: "form-control"
          = f.label :admin
        .box-footer.clearfix
          .pull-right
            =link_to "Cancel", admin_users_path
            | &nbsp;or&nbsp;
            button.btn.btn-primary type="submit" Submit
  .col-sm-8.col-sm-offset-4.col-md-3.col-md-offset-0
    - if @user.id?
      .box.box-solid
        .box-header
          h3.box-title Avatar
        .box-body
          - if @user.avatar?
            | You can change user avatar here
            br
            | or remove the current avatar to revert to #{link_to "gravatar.com", "http://gravatar.com"}
          - else
            | You can upload an avatar here
            br
            | or change it at #{link_to "gravatar.com", "http://gravatar.com"}
          hr
          button type="button" class="btn btn-default btn-sm js-choose-user-avatar-button"
            i.fa.fa-paperclip
            span  Choose File...
          | &nbsp;
          span.file_name.js-avatar-filename  File name...
          = f.file_field :avatar, class: "js-user-avatar-input hidden"
          .light The maximum file size allowed is 100KB.
          - if @user.avatar?
            hr
            = link_to 'Remove avatar', admin_user_remove_avatar_path(@user), data: { confirm: "Avatar will be removed. Are you sure?"}, method: :put, class: "btn btn-danger btn-small remove-avatar"

app/views/admin/users/_user_card.html.slim
#user-card-tpl.hide
  div class='%%card-item%%'
    .inner
      .front
        .thumbnail.user-card id='user-%%id%%'
          .card-body
            i.fa.fa-info-circle.user-info.flip-on title='click to flip me' data-toggle='tooltip' data-user_id='user-%%id%%'
            div style='text-align:center'
              img class='avatar' data-src='%%avatar_url%%' width='120' height='120'
            .truncate title='%%name%%' data-toggle='tooltip' %%name%%
            .truncate title='%%email%%' data-toggle='tooltip' %%email%%
            div
              span style="float:right"
                a class="btn btn-primary btn-sm" href="/admin/users/%%id%%/edit" title="Edit user" data-toggle='tooltip'
                  i class="fa fa-pencil"
                | &nbsp;
                a class="btn btn-danger btn-sm %%hide_delete%%" data-confirm="User will be removed. Are you sure?" data-method="delete" href="/admin/users/%%id%%" rel="nofollow" title="Delete user" data-toggle='tooltip'
                  i class="fa fa-trash-o bg-red"
      .back
        .thumbnail.user-card id='user-%%id%%'
          .card-body
            i.fa.fa-info-circle.user-info.flip-off title='click to flip me' data-toggle='tooltip' data-user_id='user-%%id%%'
            ul
              li created : %%created%%
              li last login : %%last_login%%
              li last IP : %%last_ip%%
              li sign in count : %%sign_in_count%%
        

app/views/admin/users/edit.html.slim
- @title="Edit user"
= render 'form'

app/views/admin/users/index.html.slim
- @title="Users"
.row
  .col-sm-2
    =link_to "Add a new user", new_admin_user_path, class: "btn btn-primary btn-block"

  .col-sm-10
    .box
      .box-body
        form.navbar-form
          .form-group
            input#usersFilter.form-control type='search' placeholder="Search..."
            | &nbsp;
            select#usersSort.form-control
              option value="name" data-order="asc" Sort by name
              option value="email" data-order="asc" Sort by email
              option value="created_at" data-order="desc" Sort by creation time
              option value="sign_in_count" data-order="asc" Sort by login count
              option value="current_sign_in_at" data-order="desc" Sort by login time
    = render '/shared/loading_spinner'
    #users

= render 'user_card'

app/views/admin/users/new.html.slim
- @title="Create user"
= render 'form'